apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-node-deployment
  template:
    metadata:
      labels:
        app: nginx-node-deployment

    spec:
      containers:
      - name: nginx-node-container
        image: nginx:latest
        ports:
        - containerPort: 80
  