apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer-service

spec:
  type: LoadBalancer
  selector: 
    app : nginx-Load-Balancer-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80